### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by SailReal** [bb30/learn-duel-web#15]
* [x] create vue component for help and result #8 
* [x] Define type for gameState in TypeScript #9 
* [x] Websockets have a timeout,  write ping/pong #10 
* [x] Split App component into smaller ones #11 
* [x] Rest api calls should use POST/GET accordingly #12 
* [x] Send play errors to the website #13 
* [x] implement serverctrl.restart #14
* [x] Polymer (help page) #24
* [x] Controller test #25
    * [x] mock serverctr
    * [x] fake request to routes, check response and serverctr method call
* [x] Implement game input to user mapping #18 
* [x] Make app site responsive #17 
* [x] Insert CRSF token in root vue element and use it for post requests #26
* [x] fix firefox #21 
* [x] enable csp and configure correctly #27
* [ ] write readme
* [x] speech
